FP_PATH := device/motorola/sanders/fingerprint_c1212/fp_c1212

TARGET_GENERATED_FIRMWARE_ZIP := $(TARGET_OUT_INTERMEDIATES)/ETC/fp_c1212.zip

$(TARGET_GENERATED_FIRMWARE_ZIP):
	cd $(FP_PATH) && zip -r $(TARGET_GENERATED_FIRMWARE_ZIP) *

include $(CLEAR_VARS)
LOCAL_MODULE := fp_c1212.zip
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/etc

include $(BUILD_SYSTEM)/base_rules.mk

$(LOCAL_BUILT_MODULE): $(TARGET_GENERATED_FIRMWARE_ZIP)
	@mkdir -p $(dir $@)
	@mv $(TARGET_GENERATED_FIRMWARE_ZIP) $@
